Unknown:
  - Unknown
PKS:
  - benzoxazole
  - T1PKS
  - T2PKS
  - T3PKS
  - transAT-PKS
  - hglE-KS
  - prodigiosin
  - PpyS-KS
  - arylpolyene
  - ladderane
  - HR-T2PKS
  - PUFA
  - PKS-like
  - transAT-PKS-like
  - t1pks
  - transatpks
  - t2pks
  - hglks
  - otherks
  - t3pks
Other:
  - polyhalogenated-pyrrole
  - leupeptin
  - resorcinol
  - blactam
  - 2dos
  - amglyccycl
  - aminocoumarin
  - azoxy-crosslink
  - azoxy-dimer
  - cytokinin
  - NI-siderophore
  - ectoine
  - NAGGN
  - butyrolactone
  - indole
  - lincosamides
  - nucleoside
  - phosphoglycolipid
  - melanin
  - furan
  - hserlactone
  - phenazine
  - phosphonate
  - other
  - acyl_amino_acids
  - PBDE
  - polyyne
  - betalactone
  - tropodithietic-acid
  - pyrrolidine
  - nitropropanoic_acid
  - opine-like-metallophore
  - aminopolycarboxylic-acid
  - isocyanide
  - hydrogen-cyanide
  - hydroxytropolone
  - deazapurine
  - phosphonate-like
  - fatty_acid
  - halogenated
  - cf_fatty_acid
  - siderophore
  - cf_putative
  - fused
NRPS:
  - NRPS
  - CDPS
  - fungal_CDPS
  - RCDPS
  - thioamide-NRP
  - NAPAA
  - mycosporine
  - NRP-metallophore
  - isocyanide-nrp
  - NRPS-like
  - lysine
  - nrps
Terpene:
  - terpene
  - terpene-precursor
  - quinone_isoprenoid_chain
RiPP:
  - atropopeptide
  - lanthipeptide-class-i
  - lanthipeptide-class-ii
  - lanthipeptide-class-iii
  - lanthipeptide-class-iv
  - lanthipeptide-class-v
  - lipolanthine
  - azole-containing-RiPP
  - thioamitides
  - linaridin
  - cyanobactin
  - glycocin
  - lassopeptide
  - sactipeptide
  - bottromycin
  - microviridin
  - proteusin
  - ranthipeptide
  - redox-cofactor
  - darobactin
  - triceptide
  - archaeal-RiPP
  - epipeptide
  - cyclic-lactone-autoinducer
  - spliceotide
  - RaS-RiPP
  - fungal-RiPP
  - guanidinotides
  - crocagin
  - methanobactin
  - RiPP-like
  - RRE-containing
  - fungal-RiPP-like
  - lantipeptide
  - thiopeptide
  - head_to_tail
  - lanthipeptide
  - microcin
  - TfuA-related
  - bacteriocin
  - LAP
Saccharide:
  - oligosaccharide
  - saccharide
  - cf_saccharide
