Unknown_product:
  - Unknown
NRPS:
  - nrp
  - NRP
PKS:
  - Polyketide
  - polyketide
Terpene:
  - Terpene
  - terpene
RiPP:
  - ripp
  - RiPP
Saccharide:
  - saccharide
  - Saccharide
Alkaloid:
  - Alkaloid
  - alkaloid
